[project]
name = 'Tokenized-Community-Garden-Rake-Coordination-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.efficiency-optimization]
path = 'contracts/efficiency-optimization.clar'
clarity_version = 2
epoch = 2.5

[contracts.sharing-rotation]
path = 'contracts/sharing-rotation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
